volumes:
  pnpm-store: {}
  dbdata: {}

services:
  tokens-worker:
    build:
      context: ../../..
      dockerfile: Dockerfile.mono
    working_dir: /repo/packages/tokens-worker
    command: pnpm build
    environment:
      - CHOKIDAR_USEPOLLING=1
    tty: true
    stdin_open: true
    volumes:
      - ../../..:/repo
      - pnpm-store:/root/.local/share/pnpm/store
      - /repo/node_modules
      - /repo/apps/sparkpad/client/node_modules
      - /repo/packages/tokens-worker/node_modules

  client:
    build:
      context: ../../..
      dockerfile: Dockerfile.mono
    working_dir: /repo/apps/sparkpad/client
    depends_on:
      tokens-worker:
        condition: service_completed_successfully
    command: pnpm dev --host --port 5041
    ports: ["5041:5041"]
    environment:
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
    volumes:
      - ../../..:/repo
      - pnpm-store:/root/.local/share/pnpm/store
      - /repo/node_modules
      - /repo/apps/sparkpad/client/node_modules
      - /repo/packages/tokens-worker/node_modules

  log-server:
    build:
      context: ../../..
      dockerfile: Dockerfile.mono
    working_dir: /repo/apps/sparkpad/log-server
    command: pnpm dev --host --port 5043
    ports:
      - "5043:5043"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
    volumes:
      - ../../..:/repo
      - pnpm-store:/root/.local/share/pnpm/store
      - /repo/node_modules
      - /repo/apps/sparkpad/log-server/node_modules

  server:
    build:
      context: ../../..
      dockerfile: Dockerfile.mono
    working_dir: /repo/apps/sparkpad/server
    command: pnpm dev --host --port 5042
    ports:
      - "5042:5042"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
    volumes:
      - ../../..:/repo
      - pnpm-store:/root/.local/share/pnpm/store
      - /repo/node_modules
      - /repo/apps/sparkpad/server/node_modules
      - dbdata:/repo/apps/sparkpad/server/data
