#* * * Base build config (monorepo / packages/design-system) * * */
[build]
  base    = "."
  command = "corepack enable && corepack prepare pnpm@9.12.3 --activate && pnpm i --frozen-lockfile && pnpm -w -r build && pnpm -C packages/design-system docs:build"
  publish = "packages/design-system/storybook-static"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/iframe.html"
  to = "/iframe.html"
  status = 200
[[redirects]]
  from = "/sb-preview/*"
  to = "/sb-preview/:splat"
  status = 200
[[redirects]]
  from = "/sb-manager/*"
  to = "/sb-manager/:splat"
  status = 200
