export const DEFAULT_IS_NAVIGATOR_SHOWN =
  +import.meta.env.VITE_DEFAULT_IS_NAVIGATOR_SHOWN || false;
export const DEFAULT_NAVIGATOR_WIDTH =
  +import.meta.env.VITE_DEFAULT_NAVIGATOR_WIDTH || 320;
export const DEFAULT_NAVIGATOR_MIN_WIDTH =
  +import.meta.env.VITE_DEFAULT_NAVIGATOR_MIN_WIDTH || 320;
export const DEFAULT_NAVIGATOR_MAX_WIDTH =
  +import.meta.env.VITE_DEFAULT_NAVIGATOR_MAX_WIDTH || 320;
